version: '3.1'

services:
  ttn-gateway:
    restart: always
    build: .
    container_name: ttn-gateway
    environment:
    - GATEWAY_REGION=EU
    - GATEWAY_EUI=<GATEWAY_EUI>
    - GATEWAY_LAT=<GATEWAY_LAT>
    - GATEWAY_LON=<GATEWAY_LONG>
    - GATEWAY_ALT=<GATEWAY_ALT>
    - GATEWAY_EMAIL=<MAIL>
    - GATEWAY_NAME=<NAME>
    privileged: true
    network_mode: host

